### ISSUE TITLE
Tree Image Classification using TF or Pytorch

### ISSUE THREAD

**Issue by DARK-art108** [CodeFlow201/forestTreesTagging#12]
**Task#1**

- [ ]  Implement Tree Image Classification using Tensorflow or Pytorch [No Barrier on Framework]
- [ ]  Make use of Transfer Learning[Means use Pretrained Models like Resnet's, VGG, InceptionV3]
- [ ]  Save the model in the format of model.bin or model.h5
- [ ]  Apply different Data Augmentation techniques and resizing is important.

**Dataset** [Scrap By Yourself]

The dataset contains the images of Multiple categories of Tree-like Banana, Banyan, and others. Scrap the different tree images from google make sure you have scraped a maximum of 150 from each category.

* Make a global folder, which has other folders of different categories of trees, and make sure that the folders are in alphabetical order with starting with a lower case letter.

**Comment by Aditi0102** [comment]
Hello, I would like to contribute to this issue under GSSOC'21. Please assign me this issue.

**Comment by DARK-art108** [comment]
@Aditi0102 You can go ahead with the task, raise PR, and then I will take a look at it.

**Comment by Aditi0102** [comment]
Thank you :)

**Comment by Aditi0102** [comment]
Hello @DARK-art108, I've been working on this problem and have finished training my model, but at the time of upload, Git is unable to push a .h5 file to a remote repository. I've been trying it for a few days now and I've discovered that it's because of the large file size. And let me know what you think I should do. 
Thank you so much

**Comment by DARK-art108** [comment]
@Aditi0102 zip the file drop in the Google drive with public access, and the model code file will be pushed to the repo, make sure you create a global folder and keep everything inside it and then push

**Comment by Aditi0102** [comment]
Hello @DARK-art108, I have sent a pull request regarding this issue, kindly review it.
Thank You

**Comment by saidrishya** [comment]
Hi, If the issue is still open, I would like to work on it. I am a  GSSOC participant.
